name: Deploy

on:
  push:
    branches: [deployed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Install lftp
      run: sudo apt-get install -y lftp

    - name: Setup Node
      uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: Clone Repo
      uses: actions/checkout@master
      with:
        ref: deployed

    - name: Install dependencies
      run: npm ci

    - name: Configure known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.knownHosts }}" >> ~/.ssh/known_hosts

    - name: Deploy page
      run: ./deploy.sh
      env:
        HOST: ${{ secrets.host }}
        PORT: ${{ secrets.hostPort }}
        USER: ${{ secrets.user }}
        PASSWORD: ${{ secrets.password }}
        TARGET: ${{ secrets.target }}
        PUBLIC_PATH: ${{ secrets.publicPath }}
        PURGE_URL: ${{ secrets.purgeUrl }}
